# Generated by Django 3.1.2 on 2020-11-27 02:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0002_auto_20201126_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work_day.professional')),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_day.professional')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=500)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=datetime.datetime(2020, 11, 28, 2, 18, 59, 358602, tzinfo=utc))),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_day.curriculum')),
                ('profession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work_day.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=200)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_day.joboffer')),
                ('profession', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work_day.profession')),
            ],
        ),
    ]
