# Generated by Django 3.1.2 on 2020-11-27 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0004_auto_20201127_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 22, 29, 6, 362692, tzinfo=utc)),
        ),
    ]
