# Generated by Django 3.1.2 on 2020-11-27 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0006_auto_20201127_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 22, 35, 21, 35704, tzinfo=utc)),
        ),
    ]
