# Generated by Django 3.1.2 on 2020-11-28 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0007_auto_20201127_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 19, 39, 52, 367215, tzinfo=utc)),
        ),
    ]
