# Generated by Django 3.1.2 on 2020-11-29 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0008_auto_20201128_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 1, 23, 35, 863683, tzinfo=utc)),
        ),
    ]
