# Generated by Django 3.1.2 on 2020-12-02 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0013_auto_20201130_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 0, 40, 22, 883033, tzinfo=utc)),
        ),
    ]
