# Generated by Django 3.1.2 on 2020-12-02 01:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0014_auto_20201201_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 1, 30, 52, 942806, tzinfo=utc)),
        ),
    ]
