# Generated by Django 3.1.2 on 2020-12-05 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0015_auto_20201202_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 21, 59, 18, 256552, tzinfo=utc)),
        ),
    ]
