# Generated by Django 3.1.2 on 2020-12-05 23:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0015_auto_20201202_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_day.profession'),
        ),
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 23, 39, 36, 743002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_day.profession'),
        ),
    ]
