# Generated by Django 3.1.2 on 2020-12-06 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0016_auto_20201205_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 23, 10, 3, 163499, tzinfo=utc)),
        ),
    ]
