# Generated by Django 3.1.2 on 2020-12-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0016_auto_20201205_1839'),
        ('work_day', '0017_auto_20201206_1810'),
    ]

    operations = [
    ]
