# Generated by Django 3.1.2 on 2020-12-08 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0019_auto_20201208_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 18, 57, 28, 499088, tzinfo=utc)),
        ),
    ]
