# Generated by Django 3.1.2 on 2020-12-09 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0020_auto_20201208_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='id_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 0, 18, 58, 834065, tzinfo=utc)),
        ),
    ]
