# Generated by Django 3.1.2 on 2020-12-08 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0020_auto_20201208_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 19, 1, 20, 291014, tzinfo=utc)),
        ),
    ]
