# Generated by Django 3.1.2 on 2020-12-09 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0022_auto_20201208_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
