# Generated by Django 3.1.2 on 2020-12-19 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0025_auto_20201219_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='professiontranslation',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
    ]
