# Generated by Django 3.1.2 on 2020-12-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0024_auto_20201211_2158'),
        ('work_day', '0026_auto_20201219_2209'),
    ]

    operations = [
    ]
