# Generated by Django 3.1.2 on 2020-12-22 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_day', '0027_merge_20201220_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['creation_date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='professional',
            name='birthdate',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Birthdate'),
        ),
    ]
